# Site settings
title: Dozer Zone
name: Dozer Zone
email: mail@dozer.cc
description: 'Dozer&#039;s Technology Blog'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dozer.cc" # the base hostname & protocol for your site
twitter_username: dozer47528
github_username: dozer47528

# Build settings
markdown: kramdown
pygments: true
